In [4]:
import pandas as pd
import  numpy as np

# read -> Ler
# dataframe -> Base de dados do Panda = df

df_vendas = pd.read_csv("vendas_tech.csv", low_memory=False) # encoding="latin1" --- sep=","
display(df_vendas)
df_gerente = pd.read_excel("gerentes_lojas.xlsx")
display(df_gerente)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [5]:
# INSPEÇÃO
display(df_vendas.head(10)) # head -> AS PRIMEIRAS LINHAS
display(df_vendas.tail(10)) # tail -> AS ULTIMAS LINHAS
display(df_vendas.sample(10)) # sample -> LINHAS ALEATORIAS

display(df_vendas.shape) # shape -> Para mostrar a quantidade de linhas e colunas

display(list(df_vendas.columns)) # Mostrar o nome das colunas

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,NaN
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,NaN
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053,NaN
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175,NaN
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
100090,15752,2023-03-20,Curitiba,"Monitor 27""",1200.0,1,Cliente_356,NaN
100091,4801,2023-10-29,São Paulo,Smartphone Samsung,2200.0,1,Cliente_5799,NaN
100092,89541,2023-09-01,Porto Alegre,"Monitor 27""",1200.0,1,Cliente_24144,NaN
100093,77528,2024-03-30,São Paulo,"Monitor 27""",1200.0,3,Cliente_5144,NaN
100094,32853,2024-04-10,Salvador,Smartphone Samsung,2200.0,2,Cliente_29799,NaN
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
39037,39038,2023-04-28,Belo Horizonte,iPhone 14,5500.0,1,Cliente_2310,NaN
56306,56307,2023-07-30,São Paulo,"Monitor 27""",1200.0,1,Cliente_23521,NaN
15941,15942,2023-11-16,Belo Horizonte,Teclado Mecânico,250.0,1,Cliente_24800,NaN
66164,66165,2024-03-01,Belo Horizonte,Notebook Dell,3500.0,1,Cliente_19873,NaN
80044,80045,2023-09-17,Salvador,Teclado Mecânico,250.0,1,Cliente_24629,NaN
75579,75580,2023-09-25,Rio de Janeiro,iPhone 14,5500.0,1,Cliente_28721,NaN
35582,35583,2023-12-18,Rio de Janeiro,Mouse Gamer,120.0,1,Cliente_269,NaN
22980,22981,2023-02-21,Belo Horizonte,"Monitor 27""",1200.0,1,Cliente_4749,NaN
77219,77220,2024-07-14,São Paulo,Cabo HDMI,40.0,3,Cliente_5913,NaN
99338,99339,2023-05-08,São Paulo,iPhone 14,5500.0,2,Cliente_11269,NaN

(100100, 8)

['ID_Pedido',
 'Data',
 'Loja',
 'Produto',
 'Preco_Unitario',
 'Qtd',
 'Cliente',
 'Data_Base']

In [6]:
display(df_vendas.info())
display(df_vendas.describe())

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 6.1 MB

None

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

In [7]:
# TRATAMENRO DE DADOS
df_vendas["Loja"] # selecionando coluna

# colunas
df_analise = df_vendas.drop(columns=["Data_Base"]) # EXCLUIR LINHAS OU COLUNAS
#display(df_analise)

# nulos
df_analise = df_analise.dropna() # EXCLUI VALORES VAZIOS
#display(df_analise)

# tipos de dados
df_analise["Data"] = pd.to_datetime(df_analise["Data"], format="%Y-%m-%d")

# padronização
df_analise["Loja"] = df_analise["Loja"].str.strip() # Tirar os espaços
df_analise["Loja"] = df_analise["Loja"].str.title() # Padronizar os nomes

# duplicatas
df_analise = df_analise.drop_duplicates(subset=["ID_Pedido"])




display(df_analise)
display(df_vendas.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 6.1 MB

None

In [14]:
# CRIAR NOVAS COLUNAS

# FATURAMENTO
df_analise["Faturamento"] = df_analise["Qtd"] * df_analise["Preco_Unitario"]

# FORMA DE VENDA
df_analise["Forma_de_Venda"] = np.where(df_analise["Loja"]=="Online", "Online", "Presencial") # np = if -> Analisar uma coluna e tratalar

# REGIAO
#display(df_analise["Loja"].unique()) # Visualizar uma unica coluna

dic_regioes = {
    'São Paulo': "Sudeste",
    'Belo Horizonte': "Sudeste",
    'Online': "Online",
    'Rio De Janeiro': "Sudeste",
    'Salvador': "Nordeste",
    'Recife': "Nordeste",
    'Curitiba': "Sul",
    'Porto Alegre': "Sul"
    }

df_analise["Regiao"] = df_analise["Loja"].map(dic_regioes)



display(df_analise)
display(df_analise.isna().sum())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,40.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial,Sudeste
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Presencial,Sudeste
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Presencial,Sul
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Presencial,Sul
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,250.0,Presencial,Sul

ID_Pedido         0
Data              0
Loja              0
Produto           0
Preco_Unitario    0
Qtd               0
Cliente           0
Faturamento       0
Forma_de_Venda    0
Regiao            0
dtype: int64

In [27]:
# ANALISAR -> filtrar

df_analise = df_analise.sort_values(by=["Data", "Faturamento"], ascending=True) # Ordenando do mais antigo para o mais novo
df_analise = df_analise.reset_index(drop=True) # drop=True --> jogar o index antigo para fora

# .loc -> id do pedido --> por nome da coluna e por nome da linha
id_pedido = 4

loja = df_analise.loc[3, "Loja"]
produto = df_analise.loc[3, "Produto"]
cliente = df_analise.loc[3, "Cliente"]
print(loja, produto, cliente)

# comdicional
df_id_pedido_4 = df_analise[df_analise["ID_Pedido"]==4]

# exportar pedaços da base
df_vendas_sp = df_analise[df_analise["Loja"]=="São Paulo"]
df_vendas_sp.to_csv("Vendas_SP.csv", index=False) # TRANSFORMAR ESSA TABELA EM UM ARQUIVO CSV

# exportar as vendas de 2024
df_vendas_2024 = df_analise[df_analise["Data"].dt.year==2024]

# duplas condições
df_vendas_HDMI_SUL = df_analise[(df_analise["Produto"]=="Cabo HDMI") & (df_analise["Regiao"]=="Sul")]

#display(df_analise)
#display(df_id_pedido_4)
#display(df_vendas_sp)
#display(df_vendas_2024)
display(df_vendas_HDMI_SUL)

Porto Alegre Cabo HDMI Cliente_14435

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
3,1700,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_14435,40.0,Presencial,Sul
4,49140,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_24445,40.0,Presencial,Sul
5,35599,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_18680,40.0,Presencial,Sul
7,70138,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_9348,40.0,Presencial,Sul
13,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,40.0,Presencial,Sul
...,...,...,...,...,...,...,...,...,...,...
97878,78584,2024-12-30,Curitiba,Cabo HDMI,40.0,1,Cliente_21307,40.0,Presencial,Sul
97881,75695,2024-12-30,Porto Alegre,Cabo HDMI,40.0,1,Cliente_29587,40.0,Presencial,Sul
97882,47774,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_14363,80.0,Presencial,Sul
97884,35127,2024-12-30,Curitiba,Cabo HDMI,40.0,2,Cliente_20687,80.0,Presencial,Sul
97885,64473,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_11598,80.0,Presencial,Sul

In [34]:
# ANALISE POR AGRUPAMENTO
#display(df_analise)

# ranking de faturamento por loja
analise_lojas = df_analise[["Loja", "Faturamento"]].groupby("Loja").sum()
analise_lojas = analise_lojas.sort_values(by="Faturamento", ascending=True)
analise_lojas["Faturamento"] = analise_lojas["Faturamento"].map("R${:,.2f}".format) # CODIGO DE FORMATAÇÃO
display(analise_lojas)

# ranking de produtos que mais venderam no online
df_vendas_online = df_analise[df_analise["Loja"]=="Online"]
#display(df_vendas_online)

                    Faturamento
Loja
Curitiba        R$41,121,720.00
Porto Alegre    R$41,678,460.00
Belo Horizonte  R$41,714,890.00
São Paulo       R$42,090,690.00
Recife          R$42,190,390.00
Rio De Janeiro  R$42,294,720.00
Salvador        R$42,300,610.00